//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCGPlayerKevinMohan.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Set
    {
        public int SetId { get; set; }
        public string SetName { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
    }
}
